public enum EventType
{
    BATTLE_START, BATTLE_END,
    ON_TURN_START, ON_TURN_END,

    ON_CARD_BATTLE, ON_CARD_DRAWN, ON_CARD_DISCARDED, ON_CARD_PLAY, ON_CARD_DIE, ON_CARD_CLICKED, ON_CREATURE_SUMMONED,

    ON_ENCOUNTER,
    ON_PLAYER_WIN, ON_PLAYER_LOSE
}
